#input = list("ABabACacBCbca")
#input = list("ABCbAbbacBbAaCCCBcAACCbCAbcbcccaBAAACCcbcBAbBBaCACacBabbacbacbBAcBbbCbaCBaccABbccBcACcaabCBAaBBaAbCc")
#input = list("ABCCcbaAcbCBCbBaCAbCcAaCCBCaaCABBCBBbAbaCACcAaAAcCaaAbaCCCABBCAbBBAaaBaCbCBCACaBCAABbaCBbABCBcBBbBcacAcBaABABaaccBcBaabBbCcccacBCbBbBbCaaABaCbbBbBAcCbBCbcCcacBAbCAAcaBaABCAaBCabbCbcBaCCAaaabBacCABBBBbaaBbbbcabccBbCabcBCAAcaAAcCcabbAcbbcBcaCCBCABcacCBBcbbcBAcbAbccCCaAbAbBAABcaAaccaBcBcbccAAaabbaAbaaA")
input = list("AABCBABCABCabcabcABCCBAACBCa")
input = list("AAaACcCcAbBaCabcbbAaaAacAbCCCaABcCaABcAAaCCbaabCAbbBACABABCccABAbcCccCaAbbcCACCCccCBAcaCcBccCaBbCbBBCaBaBbabCCbcbacCbabBBcccCCcacaCBBcaabACaBbBAAaBcAbaABaCCCcacbBcaacAAcbbccacbaCacbbAaBccCBAbbcBccCBcbcbCCBAcAcCBaCbBACAabCaAAaBAAAAaBCaBaAAAcCbCcbBbBbBCcbCBccBABBABCbCaCbbBABACbCcaaAABcBcaAcbcCcbaBCAaccBBcccbccbcCbAaaCBCCcbacAbcbAcCcCCBabBCcbAcccCcbACBBbaCAacCCBAcCCCcCBBBBBABBBbbBBaBcCBBbCbcAbBBbcbCACccccAcBbBCCbBBCcBaCABCcBCBaccCBAbcaabCaccCAbCaBaccbbACCAAbbBaCcCbCBbcBccCbbCCAAcbBcaCcBbBcaCcaAABBcAACCBaBCCbcCBAbbCBccaABCBaBBbbaAccCcBcaCabCBbBAcaabBBCAbBCAbcBBabCccBBacbbCbbbAbcCCABBaaCBAAaaBCbcCcAbAAAbbbBCBaCCcBbAbACcccbbcbBBBcCBbaBcAcCcAcABcAbCAaACAcbCCAbbaaaBaBbbAccABAbBaBAaAaCaAbaCaacbcbabBCAcCbbbcccaCbCccaBBbABcCCbACBacacAcCAABbCccBAAbAaBcABAbbCCAbBcbBBAAbCaCBcAAaCcbCbaccacCbaBAbacacAbACABcaBAAaaCcAaBCcbaaAcaCBBBabcbcBBcCBbBbCaabbBAcCccCbcAAABAcbcbCcCcAAabAbbBBbAccAaCaCbacBaBAacAAcaaaCcAcacBBaACCcCAAAABACaacBCccaBCCbbABCCCACbbbAaCACCcCaAbaaACccaCBcBAAaCaCCABCbAbcbAcCcbcBAAbAaABbcAcCbbccBcbBAAbCBCBcbbCcCaacacaBbCcAAACBCbAcCcCCABCaCcCcaCbAcCACCBCAAacBcacabcBBCABbBaCAAaACCBAaCCbabCCccCCCCCcbaCBbcaaBAaAaAcBBaccaBACcAaBcAbaCbBAbAacbABcccBbAaccabBbAAbAAabCbbCBAaBbcaAcAbAAACABbabaACcBCBaAbabCbCAaBcabBbBAcCaABABCCBaBbbaAccbBBAbacAaBcbcbbaBACcCCcaBBbccBcBbcaAAAABAABacAAcCcaAACccBbbAcbCaACcaAccCABBAAbcbcBCbbCaabBAAAbcAAccBcCbbCCcACAAaABBbAccCaAcbbBCacaaaACBcbCbcCBaBAacBABbcBbCACcacaAacAbcbbAAcbaCbAcABCAbacBCcAaBacBacCCaCbbcccBCBaAcACabBcbBCaAaacaBCCBcBcABaBAacaBBCCBbCcBAbBCbCbAbbbACCcCaaaCcacBBaBcBbBABccBABbBCcaCcBacaBbBABCCAACcbbCcAbbCbcBbAaACBaaBBcCBbACabbbAaAbaCCBaacbcaaaaccBCbBAcbaaCAAaaBaaBACacacaaBAAcbCCbacaaAACaBBCcbbBCBbCACaccbcBCbBbabcBbbBaaaaABABcBaBcCcCAcaCCACbbBcAcaCCbabaaAcCABcbACBacbbCCCBCACcAAAAaCcAbaBAabbCAbAbcBACCABBCBAbaccBcAbcaaAaCccABbacaabcBcccbBbCCCcAbBBCBaCaCaaABaAbCbcbBAbCCBBABAbCcBaCABBAAaBAbcBbcAcCbCbBbccaACcABBBcBabBaAcBCBbBababcbaBbAbbABAaBCAcbBaAabacbaacBAcCBbcaBAaaacBaaCBacCbbacBCAbcAcaCcCBCaCAaBaAaAaCAbCAAaaACCbacacCbBbBBACbaACaCaAcAcaaAacbBBaBbAcbBcBAbBcAABBcBaCCaAcbbbaccACBCBCcBbBCaBcCCBCAAacbaCaBbCBcacBBAACbaABAAbCaBbCCcbAbaABbAcaABabABcaaaCaABCcbBBCaaaaAaCBcBcAaaCcAAabbbbcCcabCCcccAcaCCBBABBAbcCabaaccccBcbBcacBACaAbBCBcccccBcbABAcbcAAABCaAcacabCBcCCACACACABbaABCAacAbaBCbCaCCcABABAabccCbcBbCcabCCcbBcacbbcABABCAcbCaAAaAbBBcBaBCacCbbaCBAAbcbcbbBcAbCCCAbAcaAbabBCaCccAbACAcaCCbcbaCcaBbcbcACccCbCCACcABcBbcCCCaABabcAbaABAcBaCCaBbABABABABbCBcAcbABBAAaaAaBABaCbbccaACaCBCBABaCabbbCaBBaaCCAbcBaBaCCCcBAacaccaAbaaaabaAcbaBbaBBaCCCCAAAaAbbCbCaAcCccbbCAAcAbCbaABAAbabbaaaaCBBcBCcccCbaBcCCCAAaABaBCCabbcbBcCbBCCacAcCBbACBCbBAbCbaACbabbBccCcCaBcACbABBAbBBCbCAcAbABAAccBCccbBBbBCcAcCAbCcBbabCabcbcaBBCaACbcCbccaAbBabaBcAcAcbBCAcbcBBccabaaBBcBCbbcbabABACBbabABcccCBCBBaabBbbCbacaabBBABAABCbaabAcBAcCBbcACbABbCBabCAccaBcacCBbBabAbaBCcABcBcCcCACbAbaABbAbbAababcbBAaabABbCCaBCaCbBcACcABBcAabbaaCbaBCBBCbcAbCcbaCAacbBBBBccBCcaAccbaBbbbbBaaabAbcBcaCAaCcbbAcCbCcAAbAAbCBAcCCbBacBCbBAbcAAcCaAbaabcCbbBaaaBbAbbbbCcCcbCCaBccABBcbaCbcbBCCcCcbaAcACCABAcaCbccacACbAccBacCbcAbCcCbbBcCBacccabbAbbabcAbAaBbaaCaACaCcbcBacCaaBaAccbCCbcbBaBCBBAaaBCCAcCACabBbcbaACaCBcBbAcaCababABAcBBbACcbBCCCABACABBaBCBBAbcbccCCAAcbbCbbabcabcbBCcAAaabBabacBBcbBbcbBCCABaCBccbccbCbbCAAcCCBaBcAcabBCCBcACBbACaababacbACBCaACbcBAaaCBBcabaACBBcBcacAbbBcbcaabccaAacbbcCCcacbBACAaaAAccCACBbAbbaCabbAAcccbCCBbCacabcBABACCCBAbCCBBaAbAbACbaCACBacaAbBAcaacAaBaAAAaabbBBbbAcbAaBAAabCcbbcccCBCBbaAaaBaacBBccBaCbAccCBaAcACaCaBAaCBbaACbAbaCCAaaBbBBAcCCcbAcCBcAcBCBAAcCCcCBcABbaaCbCbaCBCBAaBccabcBACBbCccAaaABcBABaBBBBCAaBbAaCaBCACBBcaCBBccbaaBCbBaCBCccBBcCbAAbaCCBcaaacBbAAaBCaAbcBbCbacBCCcABCbAccAcaBcBabbbABcbBCCbbCCABcaBabBaBCAaCCaBaaCAbcACcCAbbAaCCBCCABCCBcAbBCcAaAAACAccaaBABCacAbCcaBABacbaCcBcBBaCbAacABAcaBCCCBbaaaaBABCCBbcaCabBCBbBaCCcbABCcAbbbbACbacaCaAcccbAbCccbCAAcAcBACBAbAaAAbcBCBccbcCcAcBBbaCBCCcacBBBCbabcaaBBaaBBcBABcCcCacbAAaaAcCcaAcCACBACABaABBCBbccbcBcBcCaBCbBBABbaaaacbACcCabBAbCBbccbCCAACBAaCaBBCaAbbaaCbbcbacabCBaAAbbBBcBBCacacbBcCBBaaacBCAaAbcCccCAcBCBBCcCcBcCcACbCbaacbAAaBabcbBabCBcAbbBBbabAcBaaBcBBbBbCcCaAAaCBACBacbcaccABBcccBaAABAabCbBCaaACAabccCcCabCcaACBcAAacCAcaCabcabBBcBbBCACCBcaCBAaCBcbcbAabbbBbAbcbBBbcaAcBbAAcCABaAabCcABCacbabAbacccbabCbbBcaCCacCAAAcAcAaACabccabAAccAAAcCaBcBBCccaBBBcCCaCbAcCbAAACAbcBaCbBaCAbbbAbBbCCcCbCbaaBBAccbBcACbaCaAbAbcBcCcCCBCCccaBCAaBcaACBaBccAcaCaCcCcaAacAcACAbAacAcAcaBBCABBBCbABBBBcaCaAABAcBACcbAcbCBaabBcaAccabCaBBCcAAcaBcaABaaCCcbaCBBBBccaABabbbcbCAbcAcACbACcbaCcAbCbBbCCACaBbbcBcCCcABcBAAccabBbBcBCAcCaCBacbaCAcaaCcBaaBBBbCbaaAbCcccABACabBAbABCAAaCAAaCCCCBCcbabbacCCCcAccbbCACacbACAbCBACcAAcBbbcBbAAACccccBAAbAcBBcBCACbCcbABbaBcacbabbAacAaAccAaABACaacBCaAccABBcCAABbABcBacAbACAbabcACbCcBAccbCcAcCbCCaBBbACBBBcBaBaBCBBACaCAcBcaccBBaaAbbAAaAbCBCABabAaAbBcacAAccCbbAACCAbBaBbBacBaCAcAbcCCcabAbBACcAcaBBAacaBbcBbaaCbcabcBaCcAbcaAcbCCCAABBcbCBCcCBBBacccAAcaaAabCBCBabAaCcaACabbCcCCbAAcaaBbCBbacbBBabCaabAabCcAAcBacaAacBCaAaACAACAcAaAACCbCaCBAAbCaABAbCCAAaaAbabCaaBaaaaaBABCBBBBcBCCacbBBAbBBaABAABcaccBACcbBAccCacaAaaCcAabbCCCAaBBAcbaaCcBbBCBbaCCbCAacbABAbBCbCaBbCACcABaaAccbACaAcBacBBaBaCbACcabbaAcbbbcBbCbAbBCCcaBBbCcBccAccAbAABAACabCACaabAACccBcaACcAaCabBbBAaAccaaacAbAbcAACCaBccaCAAacAbBCACBBaAcBbBcBaaCbbccBbccBbCbaacCcACaAaACBCaccBacaacccBCAcbBBAaAaCAccccabCBBcCAacCbaAABcBcbbaCaaCAAAcacBCBaAAaCbaACcCCaccAABbccABbbbCbAAbaabAcbcBbbABaBcBCabABCCBBbCbaCaABabAaCaBaCCcAbACBacbBaCbaaBCCcbbcccBaBbbaababABCAcCcbAaCbccaAcbaCCBCBABAaACAAcAbbACaABbaaCCaCbCAbBcaCCacbCcAbCaCcbBccabcabcCCACcCbBaaCbbccbbaBAcBCcacBaAcbccbCacBaAAcbAabcCBbcBaAbBBAAAaabBACcBCBcBAbABABAbAaACaAcCbBBAcCaCCbcAAABCcAAcCAaaBcaaccaacbabbcBaAABBAcbBBBaBaCbBcAbcCCBcBBcbCCCCBcAACbAcccAacBacabCAAbBaCAbAcAAAbbBbCBAbabccBCBBaCaccAccbaCBcaAbacccbCaaAACBCCBbaaAbBBaaCbbBBcBBcCbbBbCccbCCacABaacABCcBBAcAcCaBCAbcbCbbBbAcaCAaBCBcBaCCaccbACACAacCbCbBaBBABbbaABaBaaAacbBCCAaaAcBaBCbbcCacCbCcAAbCCabCccbBaCbcCcbABccbaAABCBccBccBbCcACBcABaCAAcACbcbBbcACAAcbbbCAbCAAaabaABAbCaAaBcbAbcbbcacaAcaCACCBBCcaaCaCbacAcaabcBAaabACBaCbbCACcACcABAACcBAabcBacbbCCCbbCAACbbacaABbaBaCccbACbCBCcCCCccbbcAbCbbBcbaBBbbBBAcabCcbAbbAbBACCBAbbBBbaAaAcBAccCacaacAbbCcaAbbcaCAaCCAcaBbCaaaCaaBaAAaBAbbAaaCBBCBbCccACCAbabBBBaaabCAABBbBbcABCCAAaAAACcbbaBbABBbccBCBcaCbbcABaCaccCABbbBaaCCAbcABaaAAaCAbCaacAACAbCCCBaBBBbACcaBcAbCaaBaCcCbAAAABBcBacacaAAbBAaBCaaCBBcACbAAccBCBaaBaACacbbAABBbccbabAAaaCAcABAaCAAbCBbccbCBbCBBBaccCACCaCbcCCbcABcBbaBBbbcCaAbacCbbCAbAbCAaBcCBbaACaCACaaCbcCBCabcbabCacACbBabAcaCcBBCBAcAacACCBcCbABCcCBbCcBBbCBbBbABacCBcAaBaBAcbabbbacbcCBAaAbAccCaBabBacbCAbbaCaCbBBcaaACCBbCbAAAaBCCaAaBcAcbcbbcaaaBBACbCACCBAaCaaaaabbaaAcaCcCaCacCACcbCBaacacCBCbCaccAABaBAAcCabCCBcaCAbaabBBCcAACAACBCaBcbbaAccCcCcaAcBCCcCABCcAbcbacAaCccbBccCbBabBACCcACCCACABABcbBccBaabABBAbAcACbCcabBabCBBCaCaaBCbbBcAabABBaCBCcaBaCBBbCAabAaABAbaCcaACCaCAAaAbccCCbAAABcacaBaBAABBAAbCacbbbaaAccCaCbABCCcAcCbAcbaaABaAABbcAAcBbCbabCCACccbaACBaBBAaacaaBACBBBcaCBBCAcBcAACaABccbbbBAcaccAACAacaaBbbacAAACcAaABBBAcccCBbbbBAABcCBAcbcAcbCcBAABbABcCCcBaBCCAaCcacACAcCBBBAAbcbCABAcccAbcbcAcCCaCccaABCCAcCbCABCbcAbABacabCCbAcAabAAAcacAACccABcccBCabCaBbccccccCbbBBBCacaaABBAaCCCBBCaCBCBabCbABbCacAABaCCBACAbBabbcCaBBAcbBbCCBCAccaACabCBcbaBcABACccabbbbcbBbabABCbBAacACaCaacAccbAABAcAAcbAaAbBaaabCbaABbACCAbBAABcCBBccBbaBabCCacbabaCBBABBACaccBbCAbbBBCabABaCacCAcaBabacCbbaACacbaaccAAbAcbaCAaACcaaBACCCacBBccBCcAbAcaaAcABacCBbAaAbaaBBAccCbCbbccBCbAAcabcabBBbCCbabbbbAacAAaABABaBBbabcCaabAABCBcbaAbBcCcAcBCcccbAABBCaAABCABAcCcAaBbCBbBAbcaBcBccaAAABaACaCcbCBcBaCcAaaabbCaBbcAbBbCcbCbBAaBBBbCCbABABBbCBbBacCCBBcAcACbCCaBcAbcCAAaCccCcaaCbaaaabaccaccBbAbaCaBCaCBcbaCaAbCbbACBBCbbCAabcBcacCAbaCAbCBaAbcAcbacBabBCAcaBCCbcAAACCacCabBBabbAcbBabaCaCCCABACbACabcCabcccabCACcbbbabCcccBCCBbaBAbAaCBbBababBaaCbcbCbBAAbcaCCbaaaaaaacCbabABCBAbBaaacBBABCaAAbCABBAacCbCaCcBbacBbbcbaaAbAcbCacbcCCaBbCcAcBBccAbBBCbBcCabbaaBCAcAbACbaCBCabABCCAcCaaAACccBCbCbaaBccAABccAaBcbAbCCCccaBAbacCcaabbCbCbbcAcabCCCCABcCBCaACBCCBaaBBcAbAAbAacABcbBbCBbacaCbcABbCbccABbabaCcACAacbCabcCAacAbaBaCbcaacAAAcBbBBCAACCACACcaaAAbAcABaBcAbcBbcCaACBCAaaACBAcCcacBBcBcBBCbBBAaCBacabABbAccCaaCBbaBCaBAccBBBCBacBCaCccaaCCCaaBcaacCAbBcaBCBacaCBbabbAbAaBaCCCbbCbaBCCAcCaCAacaacCCCACBbAbBCCbbcCBcaAaCCbbcaAbCbbbcbBCaaACBBaBcbAcBabbaaBacCcCcabcCBBBbbABACBbAcaCbCabbbcBcAaCABCBbBaCCcAcBABCcCcaAacBCaCcACccBABACAaBCbcBaAbAAbbABbcCcCCaBCCCbBbbbcbbAAbCbCaBbbbAcCBcAABaCCAaaaccAbaABAabAccAccAbBBACbAcccbaCACABaaacBBCACABAAbACbcBCCcBcbbBaAbCcabCBBbcACbaABcBCaabBbaaCcBCCbCcaAacbBBbbacBbABCCBAABcaacbCacACaCcabcbCAbacAccCCACcCbCAAbBaccabaCaAAbabaaCaAabcCaBbaCAccBCBCbCAbCbabBbcACbbbcCbbbCCcABaCacaABacaaabAcBbaaBAacCAbCaaAACcbBaAAbCbBaabCbBabBcBcBAbaacCBBBCAaCcbBbAACaaCCbCaBCABccAcAbCaCCCaCcaccbaaacAbBcBbbaCcaCBccAcCBccBCcAcACBCaBBbbCCABbBBCAcAcCccABaCacbAbbbACBCCabBaabAAaAAabBcbaacBcbACBbAAAbcAcbabbcCacbAbbbcbAbCCCcBcaccCcAcBABAcCAbCbBACAAAAbbAaCcAbBAaACcccCcBbcAbacACCCABcBCaCababAbBcCAABACcccCAccCAAcbbBABacCBBACbBbccbACcBcACAaABBAcbbcabCcbBCaccBcAAbAcbBbBaabaabbcCaCCBaBBcCbBbbcbbBbCaCbcaBaaBAAcAABbbBBCcbcaaAAaCCBCABACaACCcBBcAcCAaBCcccAcbcbbaAcAAaacABBbCCBCbccbBCbcAabBBaCAaBbaBCcAbacBbcAbBcBbcbaCCACcBCaCAaccAaacbaBABBBCaccccbbBBABcABAACbbbababaAcCABaaAcbaCaAbaaCbBacaaCCcCBbccACaBAbacabBcabBBAbAcABcabBCaAaBaCCcabaCbBcBAbaBaCAabaacABcbBAACcbaBcbbbcCbaCacabCCBcaAbcbcAcbcCcccbAAbAAcaCAAbBcaBbbbBbBBCacAACCBbAaccAaaCBcCbCbACbcCCaaCABcbACbCBCAbBbCCcCaAaBbAaAcABCBBAbbcbCAACBCbaAbaAaBcAcCcCCbccBCAABBaAcCccBBAbcCbbCcCBCbBbCCcacaBabBbbAcABbCCCCcaACaccBACbCBaAacacCbCCBaAaBbaBCaBbCBBaaBcBCabCCcbBAbCBCBBBbbcAAaCabCBBBCaCccbAbabcBCaCcABCbCBCccbACAAacabcbCCBbCbCbbccBaBaAcbcACbAcABBcabaCCAcaaABaCacCAccCcaAACbcABcBcbbbbAacabCABcaBAACaaACacbbcacbbcaAcbBaACAccbCCbabbCCAbAcaCbbaBCAcBAAAAcacCBAabbcBaCcBcbcBBbbcAACacBAAaAccCbAcbAABABbabbaAcccbBCCaBbBBAbbBBABAaAACCcBcAABCbAacABcBAbbCaAabBabCaAbBbAaCbcCcaBbccacBCbAbCAaabABbaCaBAAbcaaaBaacccbaBBAbbCbaaCBbCAaAaBcBaCbbaAABaAACcbBacabbcbaBABaBABaBbAbcbBbcCccCcCcAaCbbcACAACBbcbAaacaacBbaCabCBacaBbaaBbAabBAaaCCaCacAbaCCCCbCabAaBCccbaBAccbBCaCBBacbCCCCbcbaCcABCCBAbaBacacBcCaBbcCBaAabABcBAacCacAbBabAabcBCaCCabbAAAaABBACCCbAcBbbcBCCCABacAabc")

cnt_a, cnt_b, cnt_c = 0, 0, 0
pair_a, pair_b, pair_c = 0, 0, 0
for k, v in enumerate(input):
    if v == 'A':
        cnt_a += 1
    elif v == 'B':
        cnt_b += 1
    elif v == 'C':
        cnt_c += 1
    elif v == 'a':
        pair_a += cnt_a
    elif v == 'b':
        pair_b += cnt_b
    elif v == 'c':
        pair_c += cnt_c

print("part i", pair_a)
print("part ii", pair_a + pair_b + pair_c)

print(input)





def partiii(rep, pro):
    
    pair_a, pair_b, pair_c = 0, 0, 0
    #for k, v in enumerate(input):
    for k in range(rep * len(input)):

        v = input[k%len(input)]
        st = max(k-pro, 0)
        en = min(k+pro, len(input)*rep-1)
        #print(v, k, k-pro, k+pro, st, en)
        if v == 'a':
            #print(v, k, k-pro, k+pro, st, en)       
            for ii in range(st, en+1):
                vv = input[ii%len(input)]
                if vv == 'A':
                    pair_a += 1
        elif v == 'b':
            for ii in range(st, en+1):
                vv = input[ii%len(input)]
                if vv == 'B':
                    pair_b += 1
        elif v == 'c':
            for ii in range(st, en+1):
                vv = input[ii%len(input)]
                if vv == 'C':
                    pair_c += 1
    return pair_a + pair_b + pair_c                

rep = 1000
pro = 1000

print(partiii(1, 1000))
print(partiii(2, 1000))
print(partiii(3, 1000))